### ISSUE TITLE
lti_redirect_location wrong in default install

### ISSUE THREAD

**Issue by smkeesle** [karutaproject/karuta-backend#29]
A default install of Karuta lists a property:

lti_redirect_location=/karuta-frontend/karuta/htm/list.htm

However, when a user visits this page they get a 404 error.

I believe this should be changed to:

lti_redirect_location=/karuta/karuta/htm/list.htm

**Comment by nobry** [comment]
I changed it in commit https://github.com/karutaproject/karuta-backend/commit/1a1b4bccab140634e6b8e8831d1b9a8df7dcdbc1

I was following the project naming convention, but if someone want to only update the backend, it might be simpler for them this way.
