### ISSUE TITLE
DBConnect.getRights(String, String) attempts to access a result set field with index 0

### ISSUE THREAD

**Issue by darolmar** [karutaproject/karuta-backend#52]
com.portfolio.security.DBConnect.getRights(String, String) attempts to access a result set field with index 0

A call to getXXX or updateXXX methods of a result set was made where the field index is 0. As ResultSet fields start at index 1, this is always a mistake.

**Comment by darolmar** [comment]
I attach the patch to fix this.
[DBConnect.txt](https://github.com/karutaproject/karuta-backend/files/708369/DBConnect.txt)

**Comment by nobry** [comment]
Fixed in commit https://github.com/karutaproject/karuta-backend/commit/e3773f2ca29a92fb5c93ae3055c437628971db26

Thanks
