### ISSUE TITLE
Comparison of String objects using == or != in com.portfolio.data.attachment.CompareServlet.comparaisonVraiFaux(Node, Node, Connection) 

### ISSUE THREAD

**Issue by darolmar** [karutaproject/karuta-backend#53]
Comparison of String objects using == or != in com.portfolio.data.attachment.CompareServlet.comparaisonVraiFaux(Node, Node, Connection) 

This code compares java.lang.String objects for reference equality using the == or != operators. Unless both strings are either constants in a source file, or have been interned using the String.intern() method, the same string value may be represented by two different String objects. Consider using the equals(Object) method instead.

**Comment by darolmar** [comment]
Patch to fix
[CompareServlet.txt](https://github.com/karutaproject/karuta-backend/files/708381/CompareServlet.txt)

**Comment by nobry** [comment]
Fixed in commit https://github.com/karutaproject/karuta-backend/commit/e2c005b85d65339418623463eccf9eddd5064168

Thanks
