### ISSUE TITLE
Comparison of String objects using == or != in com.portfolio.rest.RestServicePortfolio.postImportNode(String, String, String, int, String, ServletConfig, HttpServletRequest, String, String, String) 

### ISSUE THREAD

**Issue by darolmar** [karutaproject/karuta-backend#54]
Comparison of String objects using == or != in com.portfolio.rest.RestServicePortfolio.postImportNode(String, String, String, int, String, ServletConfig, HttpServletRequest, String, String, String) 

This code compares java.lang.String objects for reference equality using the == or != operators. Unless both strings are either constants in a source file, or have been interned using the String.intern() method, the same string value may be represented by two different String objects. Consider using the equals(Object) method instead.

**Comment by darolmar** [comment]
Patch to fix
[CompareServlet.txt](https://github.com/karutaproject/karuta-backend/files/708385/CompareServlet.txt)

**Comment by nobry** [comment]
Fixed in commit https://github.com/karutaproject/karuta-backend/commit/090bd539a5e2eeef5b6cb7e7383b6e19f931eb0d

Thanks
