### ISSUE TITLE
Return value of java.sql.PreparedStatement.executeQuery() ignored in com.portfolio.data.provider.MysqlDataProvider.putRRGUpdate(Connection, int, Integer, String)

### ISSUE THREAD

**Issue by darolmar** [karutaproject/karuta-backend#55]
Current code:
		try
		{
			sql = "UPDATE group_right_info "+sqlLabel+sqlPid+"WHERE grid=?";
			st = c.prepareStatement(sql);

			for( int i=0; i<text.size(); ++i )
				st.setString(i+1, text.get(i));

			st.setInt(text.size()+1, rrgId); 

			st.executeQuery();
		}

But for updates, it's better to user executeUpdate() instead.

**Comment by darolmar** [comment]
Patch to fix
[MysqlDataProvider.txt](https://github.com/karutaproject/karuta-backend/files/708399/MysqlDataProvider.txt)

**Comment by nobry** [comment]
Fixed in commit https://github.com/karutaproject/karuta-backend/commit/871dfdeb024679649445f7bd67272e98bfd199bc

Thanks
