### ISSUE TITLE
Comparison of String parameter using == or != in com.portfolio.data.provider.MysqlDataProvider.postChangeNodeParent(Connection, int, String, String) 

### ISSUE THREAD

**Issue by darolmar** [karutaproject/karuta-backend#56]
This code compares a java.lang.String parameter for reference equality using the == or != operators. Requiring callers to pass only String constants or interned strings to a method is unnecessarily fragile, and rarely leads to measurable performance gains. Consider using the equals(Object) method instead.

**Comment by darolmar** [comment]
Patch to fix
[MysqlDataProvider.txt](https://github.com/karutaproject/karuta-backend/files/708409/MysqlDataProvider.txt)

**Comment by nobry** [comment]
Fixed in commit https://github.com/karutaproject/karuta-backend/commit/69794197de80548dc4dabe3a90f7da386b8bca32

Thanks
