### ISSUE TITLE
 Comparison of String parameter using == or != in com.portfolio.security.Credential

### ISSUE THREAD

**Issue by darolmar** [karutaproject/karuta-backend#57]
This code compares a java.lang.String parameter for reference equality using the == or != operators. Requiring callers to pass only String constants or interned strings to a method is unnecessarily fragile, and rarely leads to measurable performance gains. Consider using the equals(Object) method instead.

**Comment by darolmar** [comment]
Patch to fix
[Credential.txt](https://github.com/karutaproject/karuta-backend/files/708420/Credential.txt)

**Comment by nobry** [comment]
Fixed in commit https://github.com/karutaproject/karuta-backend/commit/f5d90a895004114f4178565953c2a92cddd8a2b9

Thanks
