### ISSUE TITLE
[LTI] configuration de la variable user id

### ISSUE THREAD

**Issue by Badatos** [karutaproject/karuta-backend#68]
A propos de la connexion LTI, il est important d'utiliser la bonne variablepour faire la concordance entre l'identifiant utilisateur Karuta et celui sur le LMS.
Malheuresement, il semble que chaque LMS utilise une variable différente.

Serait-il possible de pouvoir configurer (dans configKaruta.properties) quelle variable utiliser, de manière à pouvoir connecter un maximum de LMS.

Par exemple pour Sakai la variable est "lis_person_sourcedid", et c'est celle qui est actuellement utilisée par Karuta, mais pour Moodle il faudrait plutôt utiliser "ext_user_username"
et pour BlackBoard, ce serait "custom_lis_user_username", etc...

Voir la liste des variables de chaque LMS ici :
https://developers.exlibrisgroup.com/leganto/integrations/lti/troubleshooting/user-problems/lms-username-parameter/

**Comment by nobry** [comment]
J'ai fais la modification dans le commit 1dd295bdcc758d02a023b20fbeb659bbdfc47fd6
Aussi un nouveau .war a été mis disponible sur le site web.

Je me suis demandé si il y avait un cas où une université utilisait plusieurs LMS, mais après il y aurait tout un casse-tête dans le cas où il y aurait différents nom d'utilisateur.
J'ai donc fait un simple changement et si ce cas arrive, y réfléchir un peu plus.

**Comment by Badatos** [comment]
Merci pour cette correction Nobry !
Je viens donc d'installer la dernière version du backend (2.1.4.9 du 2019-12-17). J'ai ajouté la ligne 
"lti_userid=ext_user_username" au fichier karuta-backend_config/configKaruta.properties
et enfin j'ai redémarré tomcat avec un sudo systemctl restart tomcat
Mais pourtant cela ne change rien :/ Lors de la connexion LTI depuis Moodle, Karuta semble toujours utiliser lis_person_sourcedid et non ext_user_username. Aurais-je omis quelque-chose ?

ps : Bonne année 2020 ! ;)

**Comment by nobry** [comment]
J'ai oublié de modifier d'autres partie du code qui utilisait cette variable.
Ça devrai être bon cette fois-ci (https://github.com/karutaproject/karuta-backend/commit/10329310a59823dc96a541e0c4a751fa2b32490f)

J'ai aussi compilé une version sur le site web

(Bonne année 2020!)

**Comment by Badatos** [comment]
Cette fois ca marche ! ;)
Et en ajoutant l'option "lti_create_user=y", cela crée bien l'utilisateur s'il n'existait pas.
