### ISSUE TITLE
Bug apostrophe dans Nom

### ISSUE THREAD

**Issue by Badatos** [karutaproject/karuta-backend#69]
Bonjour,
Je viens de tomber sur un bug relatif aux apostrophes avec les comptes utilisateurs.
En effet, lorsque l'on tente de créer un nouvel utilisateur (par batch) dont le nom ou le courriel contient une apostrophe, 2 cas surviennent :
- Le nom n'est pas pris en compte. Le prénom est alors répété dans le champ "Nom"
- Le courriel est tronqué à l'apostrophe.

Exemple avec "Gérard d'Aboville <gerard.d'aboville@unice.fr>"
- Son nom sera "Gérard Gérard"
- Son courriel sera "gerard.d"

Le problème apparait aussi si on modifie l'utilisateur via l'interface frontend : en validant les modifications semblent bien prises en compte, mais quand on tente d'éditer l'utilisateur, tout ce qui apparaissait après l'apostrophe a été tronqué.

**Comment by nobry** [comment]
Bonjour,
Est-ce que vous pouvez vérifier si les données dans le xml de retour est correct? Dans mes tests tout semble bon, et dans le code j'utilise les "prepareStatement" qui s'occupe de la validité des entrées.

En faisant un GET à http://{Serveur}/karuta-backend/rest/api/users/user/{numéro_utilisateur}
Vous pouvez savoir le numéro d'utilisateur en faisant un essaie de modification d'information avec la console développeur, dans l'onglet réseau.

C'est possible que la construction de l'interface au retour pose problème, par exemple avec un `"<input value='"+$valeur+"'/>"` et donc le champ est fermé prématurément.

**Comment by tlanh** [comment]
Bonjour, ce bogue est fixé dans le front-end.

**Comment by Badatos** [comment]
Merci @tlanh pour cette info. Pouvez-vous préciser dans quelle version du frontend c'est corrigé ? 
Je viens de tester Karuta-frontend : 2.4.1-b6 (2019-12-04) et le bug y est présent en tout cas.

**Comment by tlanh** [comment]
Bonjour,
Olivier a mis une nouvelle version sur eportfolium.com
http://eportfolium.com/site/wardir/karuta.war
Lan Anh

**Comment by Badatos** [comment]
Bonjour,
Je viens de tester la dernière version 2.4.1-b8 du Frontend et je confirme que le bug des apostrophe est corrigé (à la fois via batch et via le formulaire des utilisateurs). Merci à vous !

Passez une bonne journée,
